image: Visual Studio 2017
configuration: Release
cache: c:\tools\vcpkg\installed\
build_script:
- ps: >-
    cd C:/tools/vcpkg

    git pull

    vcpkg install sfml:x86-windows

    cd C:/projects/OpMon

    cmake . -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake

    cmake --build .
